language: bash

before_install:
  - git clone git://github.com/fsquillace/junest ~/junest
  - PATH=~/junest/bin:$PATH
  - junest -f -- pacman -Syu base-devel --noconfirm --ignore sudo

script:
  - junest -- makepkg -s
