language: bash

before_install:
  - git clone git://github.com/fsquillace/junest ~/junest
  - PATH=~/junest/bin:$PATH
  - junest -u -- pacman -Syu --noconfirm base $(pacman -Sgq base-devel | sed 's/sudo//')

script:
  - junest -- makepkg -s
